name: NestPay API Pipeline

on:
    push:
        branches:
            - 'develop'
            - 'release/**'
    pull_request:
        branches:
            - 'develop'
            - 'release/**'

jobs:
    test-and-publish:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write

        steps:
            # Check out the repository
            - name: Checkout code
              uses: actions/checkout@v3

            # Set up Node.js environment
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 22
                  cache: 'npm'

            # Install dependencies
            - name: Install dependencies
              run: npm install

            # Run tests
            - name: Run tests
              run: npm test

        #   # Publish to NPM (only on `release` branch and after tests pass)
        #   - name: Publish to NPM
        #     if: github.ref_name == 'release' && success()
        #     run: npm publish
        #     env:
        #       NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

        #   # Send a notification or log success
        #   - name: Notify success
        #     if: github.ref_name == 'release' && success()
        #     run: echo "Package published successfully!"
